class "Person " as Person <Customer> {
	FirstName: Maybe String
	LastName: String 
	Address: Address 
	Gender: Gender 
}
class "MyAPI" as MyAPI  {
	FirstName: Maybe String
	LastName: String 
===
  <b>api</b>: /myapi
}
class "Base" as Base  {
	Bar: Number 
}
class "Response" as Response  {
	Foo: String 
	Bar: Base 
===
  <b>api</b>: /something
}
Base --> Response : Bar