class "Person " as Person  {
	FirstName: Maybe String
	LastName: String 
	Address: Address 
	Gender: Gender 
}
class "MyAPI" as MyAPI  {
	FirstName: Maybe String
	LastName: String 
}
class "Base" as Base  {
	Bar: Number 
}
class "Response" as Response  {
	Foo: String 
	Bar: Base 
}
Base <-- Response : Bar