enum Gender {
	Male
	Female
	Other
}
class "Address" as Address  {
	Street: String 
	PostalCode: String 
	HouseNumber: Number 
	HouseNumberExtension: String 
	City: String 
	CountryCode: String 
	Country: Maybe String
--
  <b>description</b>: The address of a
 person. This is the functional
 location of where a person lives. This
 type is of course designed for the
 Dutch address system.
<b>aggregate</b>: Person
    
}
class "Person " as Person  {
	FirstName: Maybe String
	LastName: String 
	Address: Address 
	Gender: Gender 
	CustomerId: Id  <i>from Customer</i>
--
  <b>aggregate</b>: Person
    
}
Address <-- Person : Address
Gender <-- Person : Gender
Customer <|-- Person
class "Company " as Company  {
	OrganisationName: String 
	CustomerId: Id  <i>from Customer</i>
--
  <b>aggregate</b>: Company
    
}
Customer <|-- Company
class "Customer" as Customer  {
	CustomerId: Id 
--
  <b>aggregate</b>: Customer
    
}