enum undefined {
	Male
	Female
	Other
}
class "Address" as Address  {
	Street: String 
	PostalCode: String 
	HouseNumber: Number 
	HouseNumberExtension: String 
	City: String 
	CountryCode: String 
	Country: Maybe String
--
  <b>description</b>: The address of a
 person. This is the functional
 location of where a person lives. This
 type is of course designed for the
 Dutch address system.
    
}
class "Person " as Person  {
	FirstName: Maybe String
	LastName: String 
	Address: Address 
	Gender: Gender 
	CustomerId: Id  <i>from Customer</i>
}
Address --> Person : Address
Customer --|> Person
class "Company " as Company  {
	OrganisationName: String 
	CustomerId: Id  <i>from Customer</i>
}
Customer --|> Company
class "Customer" as Customer  {
	CustomerId: Id 
}