class "Currency sign value" as Currency << (T,orchid) >> {
	Sign: String 
	Value: Number 
}
class "CreditCard" as CreditCard  {
	Number: String 
	ExpirationDate: Date 
}
class "DirectDebit" as DirectDebit  {
	BankAccountNumber: String 
}
abstract "PaymentMethod" as PaymentMethod {
	CreditCard 
	DirectDebit 
}
CreditCard <-- PaymentMethod : CreditCard
DirectDebit <-- PaymentMethod : DirectDebit