abstract "Maybe a" as Maybe {
	Just a
	Nothing 
}
class "List a" as List << (T,orchid) >> {
}
class "Currency sign value" as Currency << (T,orchid) >> {
	Sign: String 
	Value: Number 
--
  <b>Currency is expressen like</b>:
 $12,00
    
}