abstract Maybe {
	Just
	Nothing
}
Just --> Maybe : Just
Nothing --> Maybe : Nothing
class List<< (T,orchid) >> {
}
class Currency<< (T,orchid) >> {
	Sign: String 
	Value: Number 
  ---
  <b>Currency is expressen like</b>:
 $12,00
    
}