abstract "Envelope" as Envelope {
	ApiMessage 
	Error 
  ---
  <b>description</b>: api
    
}
ApiMessage --> Envelope : ApiMessage
Error --> Envelope : Error
class "Message a" as Message << (T,orchid) >> {
	HttpCode: Number 
	Message: String 
	Body: a 
}
class "OtherCustomer" as OtherCustomer  {
	Something: String 
	CustomerId: Id 
}
class "ApiMessage " as ApiMessage <Message> {
	HttpCode: Number 
	Message: String 
	Body: OtherCustomer 
}
OtherCustomer --> ApiMessage : Body
Message --* ApiMessage: ALIAS
class "Error" as Error  {
	HttpCode: Number 
	Message: String 
}