abstract Maybe {
	Just
	Nothing
}
Just --> Maybe : Just
Nothing --> Maybe : Nothing
class Address {
	Street: String 
	PostalCode: String 
	HouseNumber: Number 
	HouseNumberExtension: String 
	City: String 
	CountryCode: String 
	Country: String 
}
class Person {
	FirstName: Maybe String
	LastName: String 
	Address: Address 
}
Address --> Person : Address
enum Gender {
	Male
	Female
	Other
}
class Company {
	OrganisationName: String 
}
class Customer {
	CustomerId: Id 
}