class List {
}
class FileInfo {
	Size: Number 
	LastModified: String 
	FullPath: String 
	CreatedBy: Author 
	ModifiedBy: Author 
}
class DirectoryInfo {
	Children: List FileSystemInfo
}
FileSystemInfo "0" --> "*" DirectoryInfo : List FileSystemInfo
abstract FileSystemInfo {
	FileInfo
	DirectoryInfo
}
FileInfo --> FileSystemInfo : FileInfo
DirectoryInfo --> FileSystemInfo : DirectoryInfo
enum Gender {
	Male
	Female
	Other
}
class Person {
	FirstName: String 
	Gender: Gender 
	CustomerId: Id  <i>from Customer</i>
}
Gender --> Person : Gender
Customer --|> Person
class Company {
	OrganisationName: String 
	CustomerId: Id  <i>from Customer</i>
}
Customer --|> Company
class Customer {
	CustomerId: Id 
}
abstract Envelope {
	ApiMessage
	Error
  ---
  <b>description</b>: api
    
}
ApiMessage --> Envelope : ApiMessage
Error --> Envelope : Error
class Message {
	HttpCode: Number 
	Message: String 
	Body: a 
}
class OtherCustomer {
	Something: String 
	CustomerId: Id 
	Size: Number 
}
class Error {
	HttpCode: Number 
	Message: String 
}